"""initial migration

Revision ID: 5008688d1e00
Revises: 
Create Date: 2023-09-30 22:14:56.589565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5008688d1e00"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dc_device",
        sa.Column("ext_id", sa.String(length=225), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("secret", sa.String(length=225), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ext_id"),
    )
    op.create_table(
        "dc_sensor",
        sa.Column("name", sa.String(length=225), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("alertDirection", sa.Integer(), nullable=False),
        sa.Column("upperValueRange", sa.Float(), nullable=False, default=0),
        sa.Column("lowerValueRange", sa.Float(), nullable=False, default=0),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "dc_data",
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["dc_device.ext_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["dc_sensor.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dc_data")
    op.drop_table("dc_sensor")
    op.drop_table("dc_device")
    # ### end Alembic commands ###
