# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install safety
RUN pip install safety

# Set the working directory in the container
WORKDIR /app

# Copy the entrypoint script into the container
# COPY entrypoint.sh /app/entrypoint.sh

# # Make the entrypoint script executable
# RUN chmod +x /app/entrypoint.sh

# # Specify an entrypoint script to run safety on a mounted volume
# ENTRYPOINT ["/app/entrypoint.sh"]
